version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_prueba
    environment:
      POSTGRES_USER: kosmos
      POSTGRES_PASSWORD: kosmos
      POSTGRES_DB: kosmos_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
